### ISSUE TITLE
Create Design

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Front-End#1]
Mock up needs to be created (Obviously), This should include what we intend the final product to look like, as we will present it to the client.  This will use Twitter Bootstrap and should be finalized as an HTML file, rather than an image. Though an image is welcomed, we can much better utilize and HTML file in the future.

**Comment by SwipeX** [comment]
@PepperInsure

**Comment by SwipeX** [comment]
Reference to #2

**Comment by SwipeX** [comment]
#2 closed, work on finishing design.

**Comment by SwipeX** [comment]
http://prntscr.com/8lau2c

**Comment by PepperInsure** [comment]
Wait, there's already a search bar?

**Comment by PepperInsure** [comment]
Anyway, I've got something looking a bit like what you wanted. If there's something wrong with it let me know.

**Comment by SwipeX** [comment]
@mgriner @PepperInsure I think we can close this as completed.
