### ISSUE TITLE
Set up MS MVC Project

### ISSUE THREAD

**Issue by hermetic-charm** [CISC-475-Team-2/Front-End#15]
Need to get the project into an MVC project.

**Comment by SwipeX** [comment]
Just tried this in VS and it is going to take a bit to convert from what we have to an MVC format (just a heads up).  It looks really easy to work with though, so after sprint 4, we can focus on this.

**Comment by hermetic-charm** [comment]
@SwipeX since you have been poking around with this I was wondering if you wanted to head it up?  If not my plan was to knock it out over turkey break.

**Comment by SwipeX** [comment]
@mgriner I'll commit what I have to another repo and we can finish it during break.

**Comment by SwipeX** [comment]
Check out @ https://github.com/CISC-475-Team-2/Front-End-MVC.  It is 100% barebones at the moment, however, issues are up and it is not overly complex.

**Comment by hermetic-charm** [comment]
@SwipeX Basic migration is complete, the MVC project should work now.  We also might want to move all of the issues over to that repo and start working out of that project so people don't get confused.
