### ISSUE TITLE
Improve search functionality.

### ISSUE THREAD

**Issue by hermetic-charm** [CISC-475-Team-2/Front-End#16]
Should we also allow searching on, say, email or department (e.g. IT, Marketing etc).

**Comment by PepperInsure** [comment]
Added ability to search by department.

**Comment by hermetic-charm** [comment]
Looks good.  This might be overkill but if anyone is interested in implementing an actual search algorithm (e.g. edit distance for approximate string matching like Mihcael would still find Michael even with the c and h reversed), that might be something cool.  Seems totally optional but it would be nice I think.
