### ISSUE TITLE
Set up web server

### ISSUE THREAD

**Issue by hermetic-charm** [CISC-475-Team-2/Front-End#17]
I am assuming we are going to need to set up some sort of web server to serve the front-end from the test server.

**Comment by SwipeX** [comment]
MVC API already establishes an http web server on port 80 from my understanding.

**Comment by hermetic-charm** [comment]
Very nice, haven't gotten that far yet but I like the sound of that.  Was going to start that process after this next deliverable turn-in.

**Comment by SwipeX** [comment]
We can close this as #15 covers the rest of this issue.
