### ISSUE TITLE
Better Quality Images

### ISSUE THREAD

**Issue by hermetic-charm** [CISC-475-Team-2/Front-End#18]
Need to figure out a way to get better map images, convert PDFs and Excel to SVG?

**Comment by SwipeX** [comment]
https://convertio.co/png-svg/

This may be our best bet given the time.

**Comment by hermetic-charm** [comment]
I just gave it a whirl and it works really well, looks good to me.

**Comment by hermetic-charm** [comment]
I converted the docs to SVGs and updated so I think we can close this.  Also updated the MVC version with the same content.
