### ISSUE TITLE
Make applicable text hyperlinks

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Front-End#21]
This will include:

> Email adresses (mailto:)
> Names link to profile.
> Department could lead to list of people in that department or something of that nature.

See: ![](http://i.imgur.com/jC8L7HV.png)

**Comment by PepperInsure** [comment]
Made it based off of email instead of the hardcoded email. mailto might work.

**Comment by hermetic-charm** [comment]
See #14 , closed.
