### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by hermetic-charm** [CISC-475-Team-2/Front-End#28]
Any thoughts on our presentation we will have to give next week?

**Comment by SwipeX** [comment]
We could just outline the main features and explain how we found certain libraries or functionalities to be useful.  Just a thought.

**Comment by PepperInsure** [comment]
I'll help out the length by talking about the problem we needed to solve and emoney's circumstances. Where were they moving an office to and from, again?

**Comment by hermetic-charm** [comment]
They moved from Conshohocken to Radnor.

**Comment by raserva** [comment]
Presentation Finished
