### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by hermetic-charm** [CISC-475-Team-2/Front-End#4]
We need to work out where the floor-level control should go, and what kind of control it should be (e.g. dropdown, buttons etc.).

The footer might look better if it matched the navbars color scheme, it also needs to be adjusted for mobile compatibility (doesn't look so good on phones).

**Comment by SwipeX** [comment]
We need to break down these issues into much more specific seperate issues.

**Comment by hermetic-charm** [comment]
Done.  Closing as this issue is now split into two separate issues.
