### ISSUE TITLE
Client requested user list

### ISSUE THREAD

**Issue by hermetic-charm** [CISC-475-Team-2/Front-End#5]
The client suggested we have some kind of panel that has a list of all users in scope (i.e. visible on map).

This would also be useful to display all users that match a search.

**Comment by SwipeX** [comment]
Using this format:

Profile Picture:
http://whois/Default/Thumbnail?employeeId=<ID>

Link To Full Profile:
http://whois/Default/Profile?employeeId=<ID>

(Pending updated data)

**Comment by hermetic-charm** [comment]
Closing this.  The user panel is in an operable state.  Some content may need to be adjusted later, look and feel may be adjusted but this is ready for sprint 4.
